language: php
php:
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - composer cs-check
  - vendor/bin/phpunit --coverage-clover=clover.xml
  - vendor/bin/phpstan analyse src -l 2

after_success:
  - bash <(curl -s https://codecov.io/bash)
