language: php
php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - PREFER_LOWEST="--prefer-lowest" TEST=1 CODECOV=0 STAN=0

matrix:
  include:
    - php: 7.3
      env: PREFER_LOWEST="" TEST=1 CODECOV=1 STAN=1
    - php: "7.4snapshot"
      env: PREFER_LOWEST="" TEST=1 CODECOV=0 STAN=0

before_script:
  - if [[ $TRAVIS_PHP_VERSION != '7.4snapshot' ]]; then phpenv config-rm xdebug.ini; fi
  # @see https://github.com/cakephp/cakephp/commit/249cbc3d3a00e9eca931f44ee6990312f156e6cc#diff-4dafde5c48406484f186b8294c20e12c
  - if [[ $TRAVIS_PHP_VERSION = 7.3 && $PREFER_LOWEST = '--prefer-lowest' ]]; then composer require cakephp/cakephp:3.6.13; fi
  - composer update --prefer-dist --no-interaction $PREFER_LOWEST
  - composer show -i

script:
  - if [[ $TEST = 1 && $CODECOV = 0 ]]; then vendor/bin/phpunit; fi
  - if [[ $TEST = 1 && $CODECOV = 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - |
    if [[ $STAN = 1 ]]; then
      composer cs-check
      vendor/bin/phpstan analyse
    fi

after_success:
  - if [[ $TEST = 1 && $CODECOV = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
